In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("final_datasets/encoded_dataset.csv")

In [3]:
df.head()

,Id,Name,Streams,3D Modeling,API Gateway,APL,ASP.NET,ASP.NET Core,AVG,AWS Lambda,...,Workbench,Workflows,Writing,Written Communication,X-Rays,XAMPP,Xgboost,Yoga,Zope,eSports
0,1,EESHA SAXENA,core,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,2,Jaishree Sharma,cloud computing,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,3,RITIK AGARWAL,cloud computing,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,4,PRASON POUDEL,data science,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,5,Roshan Bhatt,core,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

Id                      248
Name           Nikunj Bedia
Streams                core
3D Modeling               0
API Gateway               0
                   ...
XAMPP                     0
Xgboost                   0
Yoga                      0
Zope                      0
eSports                   1
Name: 247, Length: 1094, dtype: object